### PR TITLE
feat: dark mode

### PR DESCRIPTION
**Pull request by ArnavK-09**

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@oscarotero required?

**Comment by oscarotero** [comment]
Hi @ArnavK-09 
Thanks so much for this!

I think I'll make some tweaks in the dark colors but it's a good start.
I also think the button could go next to the "Powered by LumeCMS" text, in the same line so it doesn't generate extra scroll. What do you think? Can you do this change?

**Comment by ArnavK-09** [comment]
> Hi @ArnavK-09 
> Thanks so much for this!
> 
> I think I'll make some tweaks in the dark colors but it's a good start.
> I also think the button could go next to the "Powered by LumeCMS" text, in the same line so it doesn't generate extra scroll. What do you think? Can you do this change? @oscarotero 

### is it ok?
+ If this pr is ok to merge, kindly address dark mode color styles and make suitable choices according to lume identity 
As I'm unable to use all components

**Comment by oscarotero** [comment]
Thank you!!

**Comment by ArnavK-09** [comment]
Thanks for merging, light mode really roasts my eyes.🤠

**Pull request merged**
