### PR TITLE
Implementing changes to current_datetime

### PR DESCRIPTION
**Pull request by rmortes**
I've changed the current_datetime component to behave the way you suggested in https://github.com/lumeland/cms/issues/22#issuecomment-2344510227:

- The previous value is shown below the input (the wording is terrible, I'm a backend dev what can I say?)
- The value is updated automatically (each second) to reflect the current datetime
- The value stops updating once the field gets "dirty" (the user updates it manually)

Additionally, I've added a new component, readonly_current_datetime, that behaves how I personally think it should:

- The field is readonly to let the user know they are not supposed to change it in any way
- The value corresponds to the last time the collection was modified
- The value is updated just before the form is sent, so it changes locally for the user (they can see the collection was updated "just now") and the new value is sent with the form so the database value changes as well

Honestly, the name "readonly_current_datetime" seems terrible to me. I'm thinking "updated_datedate" or "updated_at_datetime" would be better, since this is a pretty opinionated field and the name reflects that. Wdyt?

### CODE REVIEW

**Comment by oscarotero** [comment]
Thanks Raúl.

I don't want to have two fields for the same purpose, so let's see how we can merge this.

Btw, In my computer the "clock" effect doesn't work (the value is not updated, I don't know why). Anyway, what do you think about this proposal?

- Show the previous value as you did in your proposal.
- The readonly attribute should be optional. I'd like to allow to make changes without changing the update time. 
- Like in your proposal, change the input value on submit, but only if the input hasn't been edited previously by the user.

**Comment by rmortes** [comment]
I feel like showing the previous value separate from the input, while the input is displaying the same value, may be redundant. I think I can show the previous value once the user manually updates it, let me see if I can do that

**Comment by rmortes** [comment]
Right, this is what I got:

When you first load a form (already created), the field shows the previous updatedAt value:
image

If you, without changing anything, then save the form, the current date is saved as the updatedAt value, and the field changes to reflect that:
image

If you now change manually the value, a new label appears showing the previous field value:
image

If you now save the form, the manually inputted value is saved:
image

When creating a new document, the updatedAt value works as intended. The firstly shown value is the one when the form was created, but, if you take say 5 minutes to fill it, the datetime saved will be 5 minutes later. If, instead, you opt for editing the updatedAt value before creation (so, there's no "previous" value), no label will be appended with the "Was: <datetime>" text.

I think this approach is both understandable and intuitive, and usable and flexible. The field basically works on autopilot, except when you want to override it. And, if the form designer were to forbid overriding it, it'd pretty easy adding a readonly when configuring the field. Wdyt?

**Comment by oscarotero** [comment]
It looks good to me. Only a couple of tweaks:

- I think we can remove the "Was: ..." text if the input is modified. Fields can have user-defined descriptions that can conflict with this.
-  Instead of `connectedCallback`, use the `init` function that is executed on connected.

Thanks!

**Comment by oscarotero** [comment]
I just realized that I'm using `kebab-case` instead of `snake_case` for the other field components ("choose-list", "object-list", etc).
So, can you change the component name from `current_datetime` to `current-datetime`?

**Comment by rmortes** [comment]
Done!

**Comment by oscarotero** [comment]
Thank you! 🙌

**Pull request merged**
